// <auto-generated />
using System;
using BgituGrades.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BgituGrades.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260412102111_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BgituGrades.Domain.Entities.ApiKey", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text");

                    b.Property<DateTime?>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("LookupHash")
                        .HasColumnType("text");

                    b.Property<string>("OwnerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<string>("StoredHash")
                        .HasColumnType("text");

                    b.HasKey("Key");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_ApiKey_GroupId");

                    b.HasIndex("LookupHash")
                        .HasDatabaseName("IX_ApiKey_LookupHash");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Class", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("WeekDay")
                        .HasColumnType("integer");

                    b.Property<int>("Weeknumber")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("IX_Class_DisciplineId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Class_GroupId");

                    b.HasIndex("GroupId", "DisciplineId")
                        .HasDatabaseName("IX_Class_GroupId_DisciplineId");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Discipline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Disciplines");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CourseNumber")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("StartWeekNumber")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("StudyEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StudyStartDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Mark", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<bool>("IsOverdue")
                        .HasColumnType("boolean");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.Property<int>("WorkId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Mark_StudentId");

                    b.HasIndex("WorkId")
                        .HasDatabaseName("IX_Mark_WorkId");

                    b.HasIndex("StudentId", "WorkId")
                        .HasDatabaseName("IX_Mark_StudentId_WorkId");

                    b.ToTable("Marks");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Presence", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("IsPresent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_Presence_ClassId");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("IX_Presence_DisciplineId");

                    b.HasIndex("StudentId")
                        .HasDatabaseName("IX_Presence_StudentId");

                    b.HasIndex("StudentId", "Date")
                        .HasDatabaseName("IX_Presence_StudentId_Date");

                    b.ToTable("Presences");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.ReportSnapshot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<string>("DisciplineName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("GroupCourseNumber")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Marks")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("OfficialStudentId")
                        .HasColumnType("integer");

                    b.Property<string>("Presences")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Semester")
                        .HasColumnType("integer");

                    b.Property<int>("StudentId")
                        .HasColumnType("integer");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("IX_ReportSnapshot_DisciplineId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_ReportSnapshot_GroupId");

                    b.HasIndex("GroupId", "DisciplineId")
                        .HasDatabaseName("IX_ReportSnapshot_GroupId_DisciplineId");

                    b.ToTable("ReportSnapshots");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Setting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CalendarUrl")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("OfficialGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("OfficialId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Student_GroupId");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Transfer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ClassId")
                        .HasColumnType("integer");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("NewDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("OriginalDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.HasIndex("ClassId")
                        .HasDatabaseName("IX_Transfer_ClassId");

                    b.HasIndex("DisciplineId");

                    b.HasIndex("GroupId");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Work", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<int>("DisciplineId")
                        .HasColumnType("integer");

                    b.Property<int>("GroupId")
                        .HasColumnType("integer");

                    b.Property<DateOnly>("IssuedDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("DisciplineId")
                        .HasDatabaseName("IX_Work_DisciplineId");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("IX_Work_GroupId");

                    b.HasIndex("DisciplineId", "GroupId")
                        .HasDatabaseName("IX_Work_DisciplineId_GroupId");

                    b.ToTable("Works");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Class", b =>
                {
                    b.HasOne("BgituGrades.Domain.Entities.Discipline", "Discipline")
                        .WithMany("Classes")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Group", "Group")
                        .WithMany("Classes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Mark", b =>
                {
                    b.HasOne("BgituGrades.Domain.Entities.Student", "Student")
                        .WithMany("Marks")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Work", "Work")
                        .WithMany("Marks")
                        .HasForeignKey("WorkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("Work");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Presence", b =>
                {
                    b.HasOne("BgituGrades.Domain.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Discipline", "Discipline")
                        .WithMany("Presences")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Student", "Student")
                        .WithMany("Presences")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Discipline");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Student", b =>
                {
                    b.HasOne("BgituGrades.Domain.Entities.Group", "Group")
                        .WithMany("Students")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Transfer", b =>
                {
                    b.HasOne("BgituGrades.Domain.Entities.Class", "Class")
                        .WithMany()
                        .HasForeignKey("ClassId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Discipline", "Discipline")
                        .WithMany("Transfers")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Group", "Group")
                        .WithMany("Transfers")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Class");

                    b.Navigation("Discipline");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Work", b =>
                {
                    b.HasOne("BgituGrades.Domain.Entities.Discipline", "Discipline")
                        .WithMany("Works")
                        .HasForeignKey("DisciplineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BgituGrades.Domain.Entities.Group", "Group")
                        .WithMany("Works")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Discipline");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Discipline", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Presences");

                    b.Navigation("Transfers");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Group", b =>
                {
                    b.Navigation("Classes");

                    b.Navigation("Students");

                    b.Navigation("Transfers");

                    b.Navigation("Works");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Student", b =>
                {
                    b.Navigation("Marks");

                    b.Navigation("Presences");
                });

            modelBuilder.Entity("BgituGrades.Domain.Entities.Work", b =>
                {
                    b.Navigation("Marks");
                });
#pragma warning restore 612, 618
        }
    }
}
